name: Build Dist and Upload to Wraxx

on:
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build
      run: |
        npm install
        gulp

    - name: Upload to Wraxx
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: sftp://${{ secrets.WRAXX_HOST }}
        ftp-username: ${{ secrets.WRAXX_USERNAME }}
        ftp-password: ${{ secrets.WRAXX_PASSWORD }}
        local-dir: ./dist/